export class Equipment {
	type:string;
	health:number;
	healthPct:number;
	armor:number;
	armorPct:number;
	attack:number;
	attackPct:number;
	speed:number;
	effectivenessPct:number;
	resistancePct:number; 
	critRatePct:number;
	critDamagePct:number;
	level:number;
	set:string;
	enhancementLvl:number;
	mainStat:string;
	rarity:string;
}